<a href="https://colab.research.google.com/github/sturu1/THU-PM/blob/master/Copy_of_python%EA%B8%B0%EC%B4%88(4)_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

해당 내용은 flearning의 김길호님의 강의를 바탕으로 작성되었습니다.

https://www.flearning.net/courses/6



# 1. Numpy란

> Numpy는 C언어로 구현된 파이썬 라이브러리로써, 고성능의 수치계산을 위해 제작되었습니다. Numerical Python의 줄임말이기도 한 Numpy는 **벡터 및 행렬 연산**에 있어서 매우 편리한 기능을 제공합니다.

> numpy에서는 기본적으로 **array라는 단위로 데이터를 관리**하며 이에 대해 연산을 수행합니다. array는 말그대로 행렬이라는 개념으로 생각하시면 됩니다.

> 먼저 numpy를 사용하기 위해서는 아래와 같은 코드로 numpy를 import해야 합니다.

### 1) Numpy 사용하기

In [ ]:
import numpy as np

### 2) Array 정의 및 사용하기

In [ ]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [ ]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [ ]:
type(data1), type(data2)

(list, list)

> numpy를 이용하여 array 정의하기

> 위에서 만든 python list를 이용

In [ ]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

> array의 형태(크기)를 확인할 수 있다.

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.ndim

1

> 바로 python list를 넣어 줌으로써 만들기

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
arr2.shape

(5,)

In [ ]:
arr2.ndim

1

array의 자료형을 확인할 수 있다.

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [ ]:
data2

[1, 2, 3, 3.5, 4]

In [ ]:
arr3.shape

(5,)

In [ ]:
arr3.dtype

dtype('float64')

In [ ]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr4.shape

(4, 3)

In [ ]:
arr4.ndim

2

**numpy shape**

numpy에서는 해당 array의 크기를 알 수 있다.

shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.

arr4.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.

**numpy 자료형**

arr1이나 arr2는 int64라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.

이는 arr3내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.

numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

* 부호가 있는 정수 int(8, 16, 32, 64)
* 부호가 없는 정수 uint(8 ,16, 32, 54)
* 실수 float(16, 32, 64, 128)
* 복소수 complex(64, 128, 256)
* 불리언 bool
* 문자열 string_
* 파이썬 오프젝트 object
* 유니코드 unicode_

In [ ]:
arr5 = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]],
                 [[9,10],[11,12]]])

In [ ]:
arr5.shape


(3, 2, 2)

In [ ]:
arr5.ndim

3

**2-1.** **np.zeros(), np.ones(), np.arange() 함수**


numpy에서 array를 정의할 때 사용되는 함수들이다.

아래 실습을 통해 각각이 어떻게 다른지 살펴본다.

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

### 3) Array 연산

기본적으로 numpy에서 연산을 할때는 크기가 서로 동일한 array 끼리 연산이 진행된다.

이때 같은 위치에 있는 요소들 끼리 연산이 진행된다.

In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

In [ ]:
arr2 = np.array([[10,11,12],
                 [13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
arr2.shape

**3-1. array 덧셈**

In [ ]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

**3-2. array 뺄셈**


In [ ]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

**3-3. array 곱셈**

주의하자.

행렬의 곱처럼 곱셈이 진행되는 것이 아니라 각 요소별로 곱셈이 진행된다.

In [ ]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

**3-4. array 나눗셈**

In [ ]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

**3-5. array의 브로드 캐스트**

위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,numpy에서는 브로드캐스트라는 기능을 제공한다. 브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [ ]:
arr3.shape

(3,)

In [ ]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [ ]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다. 

연산결과를 살펴보면 arr3이 [10,11,12] 에서 [[10,11,12],[10,11,12]]로 확장되어 계산되었음을 확인할 수 있다.

동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [ ]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

### 4) Array 인덱싱

numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.

이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의한다.

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0번째 요소

In [ ]:
arr1[0]

0

3번째 요소

In [ ]:
arr1[3]

3

3번째 요소부터 8번째 요소

In [ ]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

물론 1차원이 아닌 그 이상의 차원에서도 인덱싱이 가능하다.

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다. 

In [ ]:
arr2[0,0]

1

2행의 모든 요소 꺼내기

In [ ]:
arr2[2,:]

array([ 9, 10, 11, 12])

2행의 3번째 요소 꺼내기

In [ ]:
arr2[2,3]

12

모든 행의 3번째 요소 꺼내기

In [ ]:
arr2[:,3]

array([ 4,  8, 12])

특정 부분만 꺼내기

In [ ]:
print(arr2)
arr2[1:3, 1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 6,  7],
       [10, 11]])

### 5) Array boolean 인덱싱(마스크)

numpy에서는 array에 적용되는 다양한 함수가 있다.

**5-1. 하나의 array에 적용되는 함수**

In [ ]:
arr1 = np.random.randn(5,3)
arr1

각 성분의 절대값 계산하기

In [ ]:
np.abs(arr1)

각 성분의 제곱근 계산하기 ( == array ** 0.5)

In [ ]:
np.sqrt(arr1)

**5-2. 두 개의 array에 적용되는 함수**

In [ ]:
arr1

In [ ]:
arr2 = np.random.randn(5,3)
arr2

두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)

In [ ]:
np.multiply(arr1,arr2)

두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는 최소값 계산하기(maximum, minimum)

In [ ]:
np.maximum(arr1,arr2)

**6-3. 통계 함수**

통계 함수를 통해 array의 합이나 평균등을 구할 때,

추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균등을 구할 수 있다.

In [ ]:
arr1=np.random.randn(5,3)
arr1

array([[-0.46005564,  0.18198178, -2.1386053 ],
       [-1.07847607,  0.05792211,  1.64086583],
       [ 0.92643324,  0.86153575,  1.74690579],
       [-0.13068043, -0.71087449,  0.67646052],
       [-0.11034742, -0.2199008 ,  0.30027672]])

In [ ]:
arr1.shape

(5, 3)

전체 성분의 합을 계산

In [ ]:
np.sum(arr1)

1.5434415732245594

행간의 합을 계산 (1축 기준)

In [ ]:
np.sum(arr1, axis=1)

array([-2.41667917,  0.62031187,  3.53487477, -0.1650944 , -0.0299715 ])

열 간의 합을 계산(0축 기준)

In [ ]:
np.sum(arr1, axis=0)

array([-0.85312632,  0.17066435,  2.22590355])

전체 성분의 평균을 계산

In [ ]:
np.mean(arr1)

열 간의 평균을 계산 (0축 기준)

In [ ]:
np.mean(arr1, axis=0)

행 간의 평균을 계산 (1축 기준)

In [ ]:
np.mean(arr1, axis=1)

전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)


In [ ]:
np.std(arr1)

열간의 표준편차 계산 (0축 기준)

In [ ]:
np.std(arr1, axis=0)

행간의 표준편차 계산 (1축 기준)

In [ ]:
np.std(arr1, axis=1)

전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)

In [ ]:
np.argmax(arr1)

열간의 최대값이 위치한 인덱스를 반환

In [ ]:
np.argmax(arr1, axis=0)

행간의 최대값이 위치한 인덱스를 반환

In [ ]:
np.argmax(arr1, axis=1)